/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cdr;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CurrentBillingConditionPrimaryKeyComposite extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4726513009617621398L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CurrentBillingConditionPrimaryKeyComposite\",\"namespace\":\"com.cdr\",\"fields\":[{\"name\":\"MSISDN\",\"type\":\"string\"},{\"name\":\"serviceName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CurrentBillingConditionPrimaryKeyComposite> ENCODER =
      new BinaryMessageEncoder<CurrentBillingConditionPrimaryKeyComposite>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CurrentBillingConditionPrimaryKeyComposite> DECODER =
      new BinaryMessageDecoder<CurrentBillingConditionPrimaryKeyComposite>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CurrentBillingConditionPrimaryKeyComposite> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CurrentBillingConditionPrimaryKeyComposite> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CurrentBillingConditionPrimaryKeyComposite> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CurrentBillingConditionPrimaryKeyComposite>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CurrentBillingConditionPrimaryKeyComposite to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CurrentBillingConditionPrimaryKeyComposite from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CurrentBillingConditionPrimaryKeyComposite instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CurrentBillingConditionPrimaryKeyComposite fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence MSISDN;
  private java.lang.CharSequence serviceName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CurrentBillingConditionPrimaryKeyComposite() {}

  /**
   * All-args constructor.
   * @param MSISDN The new value for MSISDN
   * @param serviceName The new value for serviceName
   */
  public CurrentBillingConditionPrimaryKeyComposite(java.lang.CharSequence MSISDN, java.lang.CharSequence serviceName) {
    this.MSISDN = MSISDN;
    this.serviceName = serviceName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MSISDN;
    case 1: return serviceName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MSISDN = (java.lang.CharSequence)value$; break;
    case 1: serviceName = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'MSISDN' field.
   * @return The value of the 'MSISDN' field.
   */
  public java.lang.CharSequence getMSISDN() {
    return MSISDN;
  }


  /**
   * Sets the value of the 'MSISDN' field.
   * @param value the value to set.
   */
  public void setMSISDN(java.lang.CharSequence value) {
    this.MSISDN = value;
  }

  /**
   * Gets the value of the 'serviceName' field.
   * @return The value of the 'serviceName' field.
   */
  public java.lang.CharSequence getServiceName() {
    return serviceName;
  }


  /**
   * Sets the value of the 'serviceName' field.
   * @param value the value to set.
   */
  public void setServiceName(java.lang.CharSequence value) {
    this.serviceName = value;
  }

  /**
   * Creates a new CurrentBillingConditionPrimaryKeyComposite RecordBuilder.
   * @return A new CurrentBillingConditionPrimaryKeyComposite RecordBuilder
   */
  public static com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder newBuilder() {
    return new com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder();
  }

  /**
   * Creates a new CurrentBillingConditionPrimaryKeyComposite RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CurrentBillingConditionPrimaryKeyComposite RecordBuilder
   */
  public static com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder newBuilder(com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder other) {
    if (other == null) {
      return new com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder();
    } else {
      return new com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder(other);
    }
  }

  /**
   * Creates a new CurrentBillingConditionPrimaryKeyComposite RecordBuilder by copying an existing CurrentBillingConditionPrimaryKeyComposite instance.
   * @param other The existing instance to copy.
   * @return A new CurrentBillingConditionPrimaryKeyComposite RecordBuilder
   */
  public static com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder newBuilder(com.cdr.CurrentBillingConditionPrimaryKeyComposite other) {
    if (other == null) {
      return new com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder();
    } else {
      return new com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder(other);
    }
  }

  /**
   * RecordBuilder for CurrentBillingConditionPrimaryKeyComposite instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CurrentBillingConditionPrimaryKeyComposite>
    implements org.apache.avro.data.RecordBuilder<CurrentBillingConditionPrimaryKeyComposite> {

    private java.lang.CharSequence MSISDN;
    private java.lang.CharSequence serviceName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MSISDN)) {
        this.MSISDN = data().deepCopy(fields()[0].schema(), other.MSISDN);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.serviceName)) {
        this.serviceName = data().deepCopy(fields()[1].schema(), other.serviceName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CurrentBillingConditionPrimaryKeyComposite instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cdr.CurrentBillingConditionPrimaryKeyComposite other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.MSISDN)) {
        this.MSISDN = data().deepCopy(fields()[0].schema(), other.MSISDN);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serviceName)) {
        this.serviceName = data().deepCopy(fields()[1].schema(), other.serviceName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'MSISDN' field.
      * @return The value.
      */
    public java.lang.CharSequence getMSISDN() {
      return MSISDN;
    }


    /**
      * Sets the value of the 'MSISDN' field.
      * @param value The value of 'MSISDN'.
      * @return This builder.
      */
    public com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder setMSISDN(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.MSISDN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MSISDN' field has been set.
      * @return True if the 'MSISDN' field has been set, false otherwise.
      */
    public boolean hasMSISDN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'MSISDN' field.
      * @return This builder.
      */
    public com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder clearMSISDN() {
      MSISDN = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceName' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceName() {
      return serviceName;
    }


    /**
      * Sets the value of the 'serviceName' field.
      * @param value The value of 'serviceName'.
      * @return This builder.
      */
    public com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder setServiceName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serviceName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceName' field has been set.
      * @return True if the 'serviceName' field has been set, false otherwise.
      */
    public boolean hasServiceName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serviceName' field.
      * @return This builder.
      */
    public com.cdr.CurrentBillingConditionPrimaryKeyComposite.Builder clearServiceName() {
      serviceName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CurrentBillingConditionPrimaryKeyComposite build() {
      try {
        CurrentBillingConditionPrimaryKeyComposite record = new CurrentBillingConditionPrimaryKeyComposite();
        record.MSISDN = fieldSetFlags()[0] ? this.MSISDN : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.serviceName = fieldSetFlags()[1] ? this.serviceName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CurrentBillingConditionPrimaryKeyComposite>
    WRITER$ = (org.apache.avro.io.DatumWriter<CurrentBillingConditionPrimaryKeyComposite>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CurrentBillingConditionPrimaryKeyComposite>
    READER$ = (org.apache.avro.io.DatumReader<CurrentBillingConditionPrimaryKeyComposite>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.MSISDN);

    out.writeString(this.serviceName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.MSISDN = in.readString(this.MSISDN instanceof Utf8 ? (Utf8)this.MSISDN : null);

      this.serviceName = in.readString(this.serviceName instanceof Utf8 ? (Utf8)this.serviceName : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.MSISDN = in.readString(this.MSISDN instanceof Utf8 ? (Utf8)this.MSISDN : null);
          break;

        case 1:
          this.serviceName = in.readString(this.serviceName instanceof Utf8 ? (Utf8)this.serviceName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










