/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cdr;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MobileNumbers extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1935839956823646002L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MobileNumbers\",\"namespace\":\"com.cdr\",\"fields\":[{\"name\":\"MSISDN\",\"type\":\"string\"},{\"name\":\"companyCode\",\"type\":\"string\"},{\"name\":\"customerID\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"planID\",\"type\":\"int\"},{\"name\":\"lastUpdate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<MobileNumbers> ENCODER =
      new BinaryMessageEncoder<MobileNumbers>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MobileNumbers> DECODER =
      new BinaryMessageDecoder<MobileNumbers>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MobileNumbers> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MobileNumbers> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MobileNumbers> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MobileNumbers>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MobileNumbers to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MobileNumbers from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MobileNumbers instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MobileNumbers fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence MSISDN;
  private java.lang.CharSequence companyCode;
  private java.lang.Integer customerID;
  private int planID;
  private java.time.Instant lastUpdate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MobileNumbers() {}

  /**
   * All-args constructor.
   * @param MSISDN The new value for MSISDN
   * @param companyCode The new value for companyCode
   * @param customerID The new value for customerID
   * @param planID The new value for planID
   * @param lastUpdate The new value for lastUpdate
   */
  public MobileNumbers(java.lang.CharSequence MSISDN, java.lang.CharSequence companyCode, java.lang.Integer customerID, java.lang.Integer planID, java.time.Instant lastUpdate) {
    this.MSISDN = MSISDN;
    this.companyCode = companyCode;
    this.customerID = customerID;
    this.planID = planID;
    this.lastUpdate = lastUpdate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MSISDN;
    case 1: return companyCode;
    case 2: return customerID;
    case 3: return planID;
    case 4: return lastUpdate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MSISDN = (java.lang.CharSequence)value$; break;
    case 1: companyCode = (java.lang.CharSequence)value$; break;
    case 2: customerID = (java.lang.Integer)value$; break;
    case 3: planID = (java.lang.Integer)value$; break;
    case 4: lastUpdate = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'MSISDN' field.
   * @return The value of the 'MSISDN' field.
   */
  public java.lang.CharSequence getMSISDN() {
    return MSISDN;
  }


  /**
   * Sets the value of the 'MSISDN' field.
   * @param value the value to set.
   */
  public void setMSISDN(java.lang.CharSequence value) {
    this.MSISDN = value;
  }

  /**
   * Gets the value of the 'companyCode' field.
   * @return The value of the 'companyCode' field.
   */
  public java.lang.CharSequence getCompanyCode() {
    return companyCode;
  }


  /**
   * Sets the value of the 'companyCode' field.
   * @param value the value to set.
   */
  public void setCompanyCode(java.lang.CharSequence value) {
    this.companyCode = value;
  }

  /**
   * Gets the value of the 'customerID' field.
   * @return The value of the 'customerID' field.
   */
  public java.lang.Integer getCustomerID() {
    return customerID;
  }


  /**
   * Sets the value of the 'customerID' field.
   * @param value the value to set.
   */
  public void setCustomerID(java.lang.Integer value) {
    this.customerID = value;
  }

  /**
   * Gets the value of the 'planID' field.
   * @return The value of the 'planID' field.
   */
  public int getPlanID() {
    return planID;
  }


  /**
   * Sets the value of the 'planID' field.
   * @param value the value to set.
   */
  public void setPlanID(int value) {
    this.planID = value;
  }

  /**
   * Gets the value of the 'lastUpdate' field.
   * @return The value of the 'lastUpdate' field.
   */
  public java.time.Instant getLastUpdate() {
    return lastUpdate;
  }


  /**
   * Sets the value of the 'lastUpdate' field.
   * @param value the value to set.
   */
  public void setLastUpdate(java.time.Instant value) {
    this.lastUpdate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new MobileNumbers RecordBuilder.
   * @return A new MobileNumbers RecordBuilder
   */
  public static com.cdr.MobileNumbers.Builder newBuilder() {
    return new com.cdr.MobileNumbers.Builder();
  }

  /**
   * Creates a new MobileNumbers RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MobileNumbers RecordBuilder
   */
  public static com.cdr.MobileNumbers.Builder newBuilder(com.cdr.MobileNumbers.Builder other) {
    if (other == null) {
      return new com.cdr.MobileNumbers.Builder();
    } else {
      return new com.cdr.MobileNumbers.Builder(other);
    }
  }

  /**
   * Creates a new MobileNumbers RecordBuilder by copying an existing MobileNumbers instance.
   * @param other The existing instance to copy.
   * @return A new MobileNumbers RecordBuilder
   */
  public static com.cdr.MobileNumbers.Builder newBuilder(com.cdr.MobileNumbers other) {
    if (other == null) {
      return new com.cdr.MobileNumbers.Builder();
    } else {
      return new com.cdr.MobileNumbers.Builder(other);
    }
  }

  /**
   * RecordBuilder for MobileNumbers instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MobileNumbers>
    implements org.apache.avro.data.RecordBuilder<MobileNumbers> {

    private java.lang.CharSequence MSISDN;
    private java.lang.CharSequence companyCode;
    private java.lang.Integer customerID;
    private int planID;
    private java.time.Instant lastUpdate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cdr.MobileNumbers.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MSISDN)) {
        this.MSISDN = data().deepCopy(fields()[0].schema(), other.MSISDN);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.companyCode)) {
        this.companyCode = data().deepCopy(fields()[1].schema(), other.companyCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.customerID)) {
        this.customerID = data().deepCopy(fields()[2].schema(), other.customerID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.planID)) {
        this.planID = data().deepCopy(fields()[3].schema(), other.planID);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lastUpdate)) {
        this.lastUpdate = data().deepCopy(fields()[4].schema(), other.lastUpdate);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing MobileNumbers instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cdr.MobileNumbers other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.MSISDN)) {
        this.MSISDN = data().deepCopy(fields()[0].schema(), other.MSISDN);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyCode)) {
        this.companyCode = data().deepCopy(fields()[1].schema(), other.companyCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customerID)) {
        this.customerID = data().deepCopy(fields()[2].schema(), other.customerID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.planID)) {
        this.planID = data().deepCopy(fields()[3].schema(), other.planID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lastUpdate)) {
        this.lastUpdate = data().deepCopy(fields()[4].schema(), other.lastUpdate);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'MSISDN' field.
      * @return The value.
      */
    public java.lang.CharSequence getMSISDN() {
      return MSISDN;
    }


    /**
      * Sets the value of the 'MSISDN' field.
      * @param value The value of 'MSISDN'.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder setMSISDN(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.MSISDN = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'MSISDN' field has been set.
      * @return True if the 'MSISDN' field has been set, false otherwise.
      */
    public boolean hasMSISDN() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'MSISDN' field.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder clearMSISDN() {
      MSISDN = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyCode() {
      return companyCode;
    }


    /**
      * Sets the value of the 'companyCode' field.
      * @param value The value of 'companyCode'.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder setCompanyCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.companyCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyCode' field has been set.
      * @return True if the 'companyCode' field has been set, false otherwise.
      */
    public boolean hasCompanyCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyCode' field.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder clearCompanyCode() {
      companyCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerID' field.
      * @return The value.
      */
    public java.lang.Integer getCustomerID() {
      return customerID;
    }


    /**
      * Sets the value of the 'customerID' field.
      * @param value The value of 'customerID'.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder setCustomerID(java.lang.Integer value) {
      validate(fields()[2], value);
      this.customerID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'customerID' field has been set.
      * @return True if the 'customerID' field has been set, false otherwise.
      */
    public boolean hasCustomerID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'customerID' field.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder clearCustomerID() {
      customerID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'planID' field.
      * @return The value.
      */
    public int getPlanID() {
      return planID;
    }


    /**
      * Sets the value of the 'planID' field.
      * @param value The value of 'planID'.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder setPlanID(int value) {
      validate(fields()[3], value);
      this.planID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'planID' field has been set.
      * @return True if the 'planID' field has been set, false otherwise.
      */
    public boolean hasPlanID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'planID' field.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder clearPlanID() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastUpdate' field.
      * @return The value.
      */
    public java.time.Instant getLastUpdate() {
      return lastUpdate;
    }


    /**
      * Sets the value of the 'lastUpdate' field.
      * @param value The value of 'lastUpdate'.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder setLastUpdate(java.time.Instant value) {
      validate(fields()[4], value);
      this.lastUpdate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lastUpdate' field has been set.
      * @return True if the 'lastUpdate' field has been set, false otherwise.
      */
    public boolean hasLastUpdate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lastUpdate' field.
      * @return This builder.
      */
    public com.cdr.MobileNumbers.Builder clearLastUpdate() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MobileNumbers build() {
      try {
        MobileNumbers record = new MobileNumbers();
        record.MSISDN = fieldSetFlags()[0] ? this.MSISDN : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.companyCode = fieldSetFlags()[1] ? this.companyCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.customerID = fieldSetFlags()[2] ? this.customerID : (java.lang.Integer) defaultValue(fields()[2]);
        record.planID = fieldSetFlags()[3] ? this.planID : (java.lang.Integer) defaultValue(fields()[3]);
        record.lastUpdate = fieldSetFlags()[4] ? this.lastUpdate : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MobileNumbers>
    WRITER$ = (org.apache.avro.io.DatumWriter<MobileNumbers>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MobileNumbers>
    READER$ = (org.apache.avro.io.DatumReader<MobileNumbers>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










