/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cdr;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PlansServicesPricesPrimaryCompositeKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3295045013813966591L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlansServicesPricesPrimaryCompositeKey\",\"namespace\":\"com.cdr\",\"fields\":[{\"name\":\"planID\",\"type\":\"int\"},{\"name\":\"serviceName\",\"type\":\"string\"},{\"name\":\"billingConditionID\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PlansServicesPricesPrimaryCompositeKey> ENCODER =
      new BinaryMessageEncoder<PlansServicesPricesPrimaryCompositeKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PlansServicesPricesPrimaryCompositeKey> DECODER =
      new BinaryMessageDecoder<PlansServicesPricesPrimaryCompositeKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PlansServicesPricesPrimaryCompositeKey> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PlansServicesPricesPrimaryCompositeKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PlansServicesPricesPrimaryCompositeKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PlansServicesPricesPrimaryCompositeKey>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PlansServicesPricesPrimaryCompositeKey to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PlansServicesPricesPrimaryCompositeKey from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PlansServicesPricesPrimaryCompositeKey instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PlansServicesPricesPrimaryCompositeKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int planID;
  private java.lang.CharSequence serviceName;
  private int billingConditionID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PlansServicesPricesPrimaryCompositeKey() {}

  /**
   * All-args constructor.
   * @param planID The new value for planID
   * @param serviceName The new value for serviceName
   * @param billingConditionID The new value for billingConditionID
   */
  public PlansServicesPricesPrimaryCompositeKey(java.lang.Integer planID, java.lang.CharSequence serviceName, java.lang.Integer billingConditionID) {
    this.planID = planID;
    this.serviceName = serviceName;
    this.billingConditionID = billingConditionID;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return planID;
    case 1: return serviceName;
    case 2: return billingConditionID;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: planID = (java.lang.Integer)value$; break;
    case 1: serviceName = (java.lang.CharSequence)value$; break;
    case 2: billingConditionID = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'planID' field.
   * @return The value of the 'planID' field.
   */
  public int getPlanID() {
    return planID;
  }


  /**
   * Sets the value of the 'planID' field.
   * @param value the value to set.
   */
  public void setPlanID(int value) {
    this.planID = value;
  }

  /**
   * Gets the value of the 'serviceName' field.
   * @return The value of the 'serviceName' field.
   */
  public java.lang.CharSequence getServiceName() {
    return serviceName;
  }


  /**
   * Sets the value of the 'serviceName' field.
   * @param value the value to set.
   */
  public void setServiceName(java.lang.CharSequence value) {
    this.serviceName = value;
  }

  /**
   * Gets the value of the 'billingConditionID' field.
   * @return The value of the 'billingConditionID' field.
   */
  public int getBillingConditionID() {
    return billingConditionID;
  }


  /**
   * Sets the value of the 'billingConditionID' field.
   * @param value the value to set.
   */
  public void setBillingConditionID(int value) {
    this.billingConditionID = value;
  }

  /**
   * Creates a new PlansServicesPricesPrimaryCompositeKey RecordBuilder.
   * @return A new PlansServicesPricesPrimaryCompositeKey RecordBuilder
   */
  public static com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder newBuilder() {
    return new com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder();
  }

  /**
   * Creates a new PlansServicesPricesPrimaryCompositeKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PlansServicesPricesPrimaryCompositeKey RecordBuilder
   */
  public static com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder newBuilder(com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder other) {
    if (other == null) {
      return new com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder();
    } else {
      return new com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder(other);
    }
  }

  /**
   * Creates a new PlansServicesPricesPrimaryCompositeKey RecordBuilder by copying an existing PlansServicesPricesPrimaryCompositeKey instance.
   * @param other The existing instance to copy.
   * @return A new PlansServicesPricesPrimaryCompositeKey RecordBuilder
   */
  public static com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder newBuilder(com.cdr.PlansServicesPricesPrimaryCompositeKey other) {
    if (other == null) {
      return new com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder();
    } else {
      return new com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder(other);
    }
  }

  /**
   * RecordBuilder for PlansServicesPricesPrimaryCompositeKey instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlansServicesPricesPrimaryCompositeKey>
    implements org.apache.avro.data.RecordBuilder<PlansServicesPricesPrimaryCompositeKey> {

    private int planID;
    private java.lang.CharSequence serviceName;
    private int billingConditionID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.planID)) {
        this.planID = data().deepCopy(fields()[0].schema(), other.planID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.serviceName)) {
        this.serviceName = data().deepCopy(fields()[1].schema(), other.serviceName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.billingConditionID)) {
        this.billingConditionID = data().deepCopy(fields()[2].schema(), other.billingConditionID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing PlansServicesPricesPrimaryCompositeKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cdr.PlansServicesPricesPrimaryCompositeKey other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.planID)) {
        this.planID = data().deepCopy(fields()[0].schema(), other.planID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serviceName)) {
        this.serviceName = data().deepCopy(fields()[1].schema(), other.serviceName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.billingConditionID)) {
        this.billingConditionID = data().deepCopy(fields()[2].schema(), other.billingConditionID);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'planID' field.
      * @return The value.
      */
    public int getPlanID() {
      return planID;
    }


    /**
      * Sets the value of the 'planID' field.
      * @param value The value of 'planID'.
      * @return This builder.
      */
    public com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder setPlanID(int value) {
      validate(fields()[0], value);
      this.planID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'planID' field has been set.
      * @return True if the 'planID' field has been set, false otherwise.
      */
    public boolean hasPlanID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'planID' field.
      * @return This builder.
      */
    public com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder clearPlanID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceName' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceName() {
      return serviceName;
    }


    /**
      * Sets the value of the 'serviceName' field.
      * @param value The value of 'serviceName'.
      * @return This builder.
      */
    public com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder setServiceName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.serviceName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceName' field has been set.
      * @return True if the 'serviceName' field has been set, false otherwise.
      */
    public boolean hasServiceName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serviceName' field.
      * @return This builder.
      */
    public com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder clearServiceName() {
      serviceName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'billingConditionID' field.
      * @return The value.
      */
    public int getBillingConditionID() {
      return billingConditionID;
    }


    /**
      * Sets the value of the 'billingConditionID' field.
      * @param value The value of 'billingConditionID'.
      * @return This builder.
      */
    public com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder setBillingConditionID(int value) {
      validate(fields()[2], value);
      this.billingConditionID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'billingConditionID' field has been set.
      * @return True if the 'billingConditionID' field has been set, false otherwise.
      */
    public boolean hasBillingConditionID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'billingConditionID' field.
      * @return This builder.
      */
    public com.cdr.PlansServicesPricesPrimaryCompositeKey.Builder clearBillingConditionID() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PlansServicesPricesPrimaryCompositeKey build() {
      try {
        PlansServicesPricesPrimaryCompositeKey record = new PlansServicesPricesPrimaryCompositeKey();
        record.planID = fieldSetFlags()[0] ? this.planID : (java.lang.Integer) defaultValue(fields()[0]);
        record.serviceName = fieldSetFlags()[1] ? this.serviceName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.billingConditionID = fieldSetFlags()[2] ? this.billingConditionID : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PlansServicesPricesPrimaryCompositeKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<PlansServicesPricesPrimaryCompositeKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PlansServicesPricesPrimaryCompositeKey>
    READER$ = (org.apache.avro.io.DatumReader<PlansServicesPricesPrimaryCompositeKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.planID);

    out.writeString(this.serviceName);

    out.writeInt(this.billingConditionID);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.planID = in.readInt();

      this.serviceName = in.readString(this.serviceName instanceof Utf8 ? (Utf8)this.serviceName : null);

      this.billingConditionID = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.planID = in.readInt();
          break;

        case 1:
          this.serviceName = in.readString(this.serviceName instanceof Utf8 ? (Utf8)this.serviceName : null);
          break;

        case 2:
          this.billingConditionID = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










